# Generated by Django 5.0.6 on 2024-05-16 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(default='example@mail.com', max_length=254)),
                ('confirm_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TK', 'Tanks'), ('HL', 'Healers'), ('DD', 'Damage Dealer'), ('MR', 'Merchants'), ('GM', 'Guild Masters'), ('QG', 'Quest Givers'), ('BS', 'Blacksmiths'), ('TN', 'Tanners'), ('PM', 'Potion Makers'), ('SM', 'Spell Masters')], default='TK', max_length=2)),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField(default='Your text')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Your response')),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardapp.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
