# Generated by Django 5.0.6 on 2024-05-17 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_images_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
