# Generated by Django 5.0.6 on 2024-05-20 07:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0006_annresponse_submit_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='AnnResponse',
            new_name='PostReply',
        ),
    ]
